# Macro to configure MPI
MACRO ( CONFIGURE_MPI )
    CHECK_ENABLE_FLAG( USE_MPI 1 )
    MESSAGE("MPIEXEC = ${MPIEXEC}")
    IF ( USE_MPI )
        MESSAGE( "Configuring MPI" )
        IF ( MPIEXEC )
            SET( MPIEXEC_EXECUTABLE ${MPIEXEC} )
        ENDIF()
        # Write mpi test
        SET( MPI_TEST_SRC "${CMAKE_CURRENT_BINARY_DIR}/test_mpi.cpp" )
        FILE(WRITE  ${MPI_TEST_SRC} "#include <mpi.h>\n" )
        FILE(APPEND ${MPI_TEST_SRC} "int main(int argc, char** argv) {\n" )
        FILE(APPEND ${MPI_TEST_SRC} "    MPI_Init(&argc,&argv);\n")
        FILE(APPEND ${MPI_TEST_SRC} "    MPI_Finalize();\n" )
        FILE(APPEND ${MPI_TEST_SRC} "}\n" )
        # Search for MPI
        IF ( NOT MPI_SKIP_SEARCH )
            FIND_PACKAGE( MPI )
            IF ( NOT MPI_FOUND )
                MESSAGE( FATAL_ERROR "CMake did not find MPI, if building without MPI set USE_MPI to false (default is true)" )
            ENDIF()
        ELSE()
            # Test the compile
            FOREACH ( tmp C CXX Fortran )
                IF ( CMAKE_${tmp}_COMPILER )
                    SET( TMP_FLAGS -DINCLUDE_DIRECTORIES=${MPI_CXX_INCLUDE_PATH} )
                    TRY_COMPILE( MPI_TEST_${tmp} ${CMAKE_CURRENT_BINARY_DIR} ${MPI_TEST_SRC}
                        CMAKE_FLAGS ${TMP_FLAGS}
                        LINK_OPTIONS ${MPI_CXX_LINK_FLAGS}
                        LINK_LIBRARIES ${MPI_CXX_LIBRARIES}
                        OUTPUT_VARIABLE OUT_TXT)
                    IF ( NOT ${MPI_TEST_${tmp}} )
                        MESSAGE( FATAL_ERROR "Skipping MPI search and default compile fails:\n${OUT_TXT}" )
                    ENDIF()
                    SET( MPI_C_FOUND TRUE )
                    SET( MPI_CXX_FOUND TRUE )
                    SET( MPI_Fortran_FOUND TRUE )
                ENDIF()
            ENDFOREACH()
        ENDIF()
        # Try and set MPI include directories
        ADD_MPI_FLAGS()
        # Set the MPI languages
        SET( MPI_LANG C CXX Fortran )
        FOREACH( tmp ${MPI_LANG} )
            STRING( STRIP "${MPI_${tmp}_COMPILE_FLAGS}" MPI_${tmp}_COMPILE_FLAGS )
            STRING( STRIP "${MPI_${tmp}_LINK_FLAGS}" MPI_${tmp}_LINK_FLAGS )
            STRING( STRIP "${MPI_${tmp}_LIBRARIES}" MPI_${tmp}_LIBRARIES )
            MESSAGE( "   MPI_${tmp}_FOUND = ${MPI_${tmp}_FOUND}" )
            MESSAGE( "   MPI_${tmp}_COMPILER = ${MPI_${tmp}_COMPILER}" )
            MESSAGE( "   MPI_${tmp}_COMPILE_FLAGS = ${MPI_${tmp}_COMPILE_FLAGS}" )
            MESSAGE( "   MPI_${tmp}_INCLUDE_DIRS = ${MPI_${tmp}_INCLUDE_DIRS}" )
            MESSAGE( "   MPI_${tmp}_LINK_FLAGS = ${MPI_${tmp}_LINK_FLAGS}" )
            MESSAGE( "   MPI_${tmp}_LIBRARIES = ${MPI_${tmp}_LIBRARIES}" )
            MESSAGE( "   MPI_${tmp}_HEADER_DIR = ${MPI_${tmp}_HEADER_DIR}" )
        ENDFOREACH()
        MESSAGE( "   MPIEXEC = ${MPIEXEC}" )
        MESSAGE( "   MPIEXEC_NUMPROC_FLAG = ${MPIEXEC_NUMPROC_FLAG}" )
        MESSAGE( "   MPIEXEC_PREFLAGS = ${MPIEXEC_PREFLAGS}" )
        MESSAGE( "   MPIEXEC_POSTFLAGS = ${MPIEXEC_POSTFLAGS}" )
        IF ( NOT MPI_C_FOUND AND NOT MPI_CXX_FOUND AND NOT MPI_Fortran_FOUND )
            MESSAGE( FATAL_ERROR "MPI not found" )
        ENDIF()
        # Perform a final test compilation
        SET( TMP_FLAGS ${MPI_${tmp}_COMPILE_FLAGS} -DINCLUDE_DIRECTORIES=${MPI_CXX_INCLUDE_DIRS} )
        TRY_COMPILE( MPI_TEST ${CMAKE_CURRENT_BINARY_DIR} ${MPI_TEST_SRC}
            CMAKE_FLAGS ${TMP_FLAGS}
            -D"LINK_OPTIONS=${MPI_CXX_LINK_FLAGS}"
            LINK_LIBRARIES ${MPI_CXX_LIBRARIES}
            OUTPUT_VARIABLE OUT_TXT )
        IF ( NOT MPI_TEST )
            MESSAGE( FATAL_ERROR "Compiling MPI test fails:\n${OUT_TXT}" )
        ENDIF()
    ENDIF()
    IF ( USE_MPI AND NOT MPIEXEC )
        MESSAGE( FATAL_ERROR "Unable to find MPIEXEC, please set it before continuing" )
    ENDIF()
ENDMACRO()


# Function to try and add MPI include flags
FUNCTION ( ADD_MPI_FLAGS )
    IF ( MPI_CXX_INCLUDE_DIRS )
        RETURN()
    ENDIF()
    SET( MPI_ARGS )
    # Test if we are using cray wrappers
    EXECUTE_PROCESS(COMMAND ${CMAKE_CXX_COMPILER} --cray-print-opts RESULT_VARIABLE flag ERROR_QUIET OUTPUT_VARIABLE out )
    IF ( "${flag}" STREQUAL "0" )
        separate_arguments( MPI_ARGS NATIVE_COMMAND ${out} )
    ENDIF()
    # Test if we can use mpi --show
    EXECUTE_PROCESS(COMMAND ${CMAKE_CXX_COMPILER} --show RESULT_VARIABLE flag ERROR_QUIET OUTPUT_VARIABLE out )
    IF ( "${flag}" STREQUAL "0" )
        separate_arguments( MPI_ARGS NATIVE_COMMAND ${out} )
    ENDIF()
    IF ( NOT MPI_ARGS )
        RETURN()
    ENDIF()
    # Parse the arguments
    FOREACH( tmp ${MPI_ARGS} )
        IF ( "${tmp}" MATCHES "^-I" )
            STRING( REGEX REPLACE "^-I" "" tmp "${tmp}" )
            SET( MPI_CXX_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} ${tmp} )
        ELSEIF ( "${tmp}" MATCHES "^-L" )
            SET( MPI_CXX_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} ${tmp} )
        ELSEIF ( "${tmp}" MATCHES "^-l" )
            SET( MPI_CXX_LIBRARIES ${MPI_CXX_LIBRARIES} ${tmp} )
        ENDIF()
    ENDFOREACH()
    SET( MPI_CXX_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} PARENT_SCOPE )
    SET( MPI_CXX_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE )
    SET( MPI_CXX_LIBRARIES ${MPI_CXX_LIBRARIES} PARENT_SCOPE )
    IF ( NOT MPI_C_INCLUDE_DIRS )
        SET( MPI_C_LINK_FLAGS ${MPI_CXX_LINK_FLAGS} PARENT_SCOPE )
        SET( MPI_C_INCLUDE_DIRS ${MPI_CXX_INCLUDE_DIRS} PARENT_SCOPE )
        SET( MPI_C_LIBRARIES ${MPI_CXX_LIBRARIES} PARENT_SCOPE )
    ENDIF()
ENDFUNCTION()
